import os
import torch
from openvoice import se_extractor
from openvoice.api import BaseSpeakerTTS, ToneColorConverter
import time

ckpt_base = 'checkpoints/base_speakers/EN'
ckpt_converter = 'checkpoints/converter'
device="xpu"
output_dir = 'outputs'

st = time.time()
base_speaker_tts = BaseSpeakerTTS(f'{ckpt_base}/config.json', device=device)
end = time.time()
print(f"init - 1 = {end - st} s")
st = time.time()
base_speaker_tts.load_ckpt(f'{ckpt_base}/checkpoint.pth')
end = time.time()
print(f"init - 1 = {end - st} s")

st = time.time()
tone_color_converter = ToneColorConverter(f'{ckpt_converter}/config.json', device=device)
tone_color_converter.load_ckpt(f'{ckpt_converter}/checkpoint.pth')
end = time.time()
print(f"init - 2 = {end - st} s")

os.makedirs(output_dir, exist_ok=True)


st = time.time()
source_se = torch.load(f'{ckpt_base}/en_default_se.pth').to(device)
end = time.time()
print(f"init - 3 = {end - st} s")

reference_speaker = 'TaylorSwift.wav' # This is the voice you want to clone
target_se, audio_name = se_extractor.get_se(reference_speaker, tone_color_converter, target_dir='processed', vad=True)

save_path = f'{output_dir}/output_en_default.wav'

# Run the base speaker tts
st = time.time()
text = "This audio is generated by OpenVoice1."
src_path = f'{output_dir}/tmp5.wav'
base_speaker_tts.tts(text, src_path, speaker='default', language='English', speed=1.0)
end = time.time()
print(f"inference = {end - st} s")
st = time.time()
text = "This audio is generated by OpenVoice2."
src_path = f'{output_dir}/tmp6.wav'
base_speaker_tts.tts(text, src_path, speaker='default', language='English', speed=1.0)
end = time.time()
print(f"inference = {end - st} s")

"""
# Run the tone color converter
encode_message = "@MyShell"
try:
    tone_color_converter.convert(
        audio_src_path=src_path,
        src_se=source_se,
        tgt_se=target_se,
        output_path=save_path,
        message=encode_message)
except Exception as e:
    print("Error during tone color conversion:", e)

source_se = torch.load(f'{ckpt_base}/en_style_se.pth').to(device)
save_path = f'{output_dir}/output_whispering.wav'

# Run the base speaker tts
text = "This audio is generated by OpenVoice."
src_path = f'{output_dir}/tmp4.wav'
base_speaker_tts.tts(text, src_path, speaker='whispering', language='English', speed=0.9)

# Run the tone color converter
encode_message = "@MyShell"
try:
    tone_color_converter.convert(
        audio_src_path=src_path,
        src_se=source_se,
        tgt_se=target_se,
        output_path=save_path,
        message=encode_message)
except Exception as e:
    print("Error during tone color conversion:", e)
"""
